server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.102.193.232:3306/SpringCloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: Qaz.1995

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.yjf.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #¼¯Èº°æ
  instance:
    instance-id: payment8001
    prefer-ip-address: true
